import AppKit
import Foundation

/// 决定一次剪贴板变更是否允许入库。
///
/// 剪贴板历史以明文存储，若把密码管理器复制的密码记下来，等于把密码库摊开在磁盘上。
/// 这是本工具最高优先级的安全约束，采用三层独立判据，任一命中即跳过。
enum PrivacyFilter {

    /// 业界通用的"敏感内容"剪贴板标记。密码管理器复制时会附加此类型，
    /// 约定见 nspasteboard.org。
    static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// 明确跳过的来源 app。命中前缀即匹配，覆盖同一家的多个 bundle。
    static let blockedSourcePrefixes: [String] = [
        "com.1password",            // 1Password
        "com.agilebits",            // 1Password 旧版
        "com.bitwarden",            // Bitwarden
        "org.keepassxc",            // KeePassXC
        "com.apple.keychainaccess", // 钥匙串访问
        "in.sinew.Enpass",          // Enpass
        "com.dashlane",             // Dashlane
        "com.lastpass",             // LastPass
        "com.stickypassword",       // Sticky Password
        "com.callpod.keeper",       // Keeper
        "com.mseven",               // mSecure
    ]

    /// 临时内容标记：其他剪贴板工具用它表示"此内容不应被记录"。
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")

    /// 判断当前剪贴板内容是否应跳过记录。
    ///
    /// - Parameters:
    ///   - types: 剪贴板当前声明的类型列表。
    ///   - sourceBundleID: 复制时的前台 app bundle id，取不到时传 nil。
    ///   - userBlocklist: 用户在偏好设置中自行追加的 bundle id 前缀。
    static func shouldSkip(types: [NSPasteboard.PasteboardType],
                           sourceBundleID: String?,
                           userBlocklist: [String] = []) -> Bool {
        // 第一层：敏感内容标记
        let typeSet = Set(types.map { $0.rawValue })
        for t in concealedTypes where typeSet.contains(t.rawValue) { return true }
        // 第二层：临时内容标记
        if typeSet.contains(transientType.rawValue) { return true }
        // 第三层：来源 app 黑名单
        if let id = sourceBundleID?.lowercased(), !id.isEmpty {
            let all = blockedSourcePrefixes + userBlocklist
            for prefix in all where !prefix.isEmpty && id.hasPrefix(prefix.lowercased()) {
                return true
            }
        }
        return false
    }
}
